default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: apartment-finder_development

test:
  <<: *default
  database: apartment-finder_test

production:
  <<: *default
  database: apartment-finder_production
  username: apartment-finder
  password: <%= ENV['APARTMENT-FINDER_DATABASE_PASSWORD'] %>
