# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec023931b52dff943d2c0f1c10409c79425dedee2bfd6bea37e9b12350911ac5651797fa4cf45d23600c5f238f396514bacde08dc05355a7f91ae569196385d

test:
  secret_key_base: 72b385698819fba85b3a1fc96817d0caa09ffe35a2aff2aac7c86af832cb1b8f61e4ca509450691ffc77654756daee7edd756849a2174d6379f297f2e8b653a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
